enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
build-mode = "module"
 
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Custom branding' 'Change header'"
build-mode = "both"
